label = "English"
title = "Glosso Studio"
description = "Independent open-source projects by IgnacioLD."

[params]
  displayName = "EN"
  isoCode = "en"

  [params.author]
    name = "Glosso Studio"
    headline = "Independent Open-Source Software"

  [[params.author.links]]
    github = "https://github.com/IgnacioLD"
  [[params.author.links]]
    gitlab = "https://gitlab.com/shirobyte421/glosso-studio"
  [[params.author.links]]
    website = "https://ignacio.tech"

  [params.homepage]
    showRecent = true

  [params.footer]
    showCopyright = false
