[[main]]
  name = "Projects"
  url = "/"
  weight = 5

[[main]]
  name = "Glosso Studio"
  url = "/features/"
  weight = 10

[[main]]
  name = "TransitOS"
  url = "/transitos/"
  weight = 15

[[main]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/IgnacioLD"
  weight = 40
  params = { icon = "github", icon_pack = "fab" }

[[main]]
  name = "GitLab"
  url = "https://gitlab.com/shirobyte421/glosso-studio"
  weight = 50
  params = { icon = "gitlab", icon_pack = "fab" }
