# Core settings
autoSwitchAppearance = true
defaultAppearance = "dark"

[header]
  layout = "fixed"

[footer]
  showCopyright = false
  showThemeAttribution = false
  showRSS = true

[homepage]
  layout = "landing"
  showRecent = false
  showRecentItems = 3
  showRecentTitle = "Latest Project Updates"

[article]
  showDate = true
  showReadingTime = true
  showAuthor = false
  showTaxonomies = true

[appearance]
  themeColor = "#6366F1"
