baseURL = 'https://glossostudio.com/'
languageCode = 'en-us'
title = 'Glosso Studio'
theme = 'PaperMod'

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  env = "production"
  description = "Independent open-source projects by IgnacioLD. Privacy-first software."
  author = "IgnacioLD"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
